_core:
  default_config_hash: LqXuXXQCTd1NWw7dGLef0PCi3_aEEWQuogAblo4hHaE
hotlink: false
origin: 'https://dev2.environmentandurbanization.org'
origin_dir: sites/default/files
proxy_headers: ''
use_imagecache_root: false
verify: false
excluded_extensions: ''
